---
title: "Mathematics for the Movement in Engineering"
subtitle: "Session 00"  
author: 
  - "Alejandro Ucan"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#000080",
  secondary_color = "#f2f3f4",
  inverse_header_color = "#00147e"
)
```

```{r xaringan-editable, echo=FALSE}
xaringanExtra::use_editable(expires = 1)
xaringanExtra::use_scribble()
```
# The Professor

### Alejandro Ucan Puc <br/>
- Ph.D. with specialization in Mathematics. <br/><br/>
- Interests: Dynamical systems, Geometry and Topology. <br/><br/>
- Mail: alejandro.ucan-puc@tec.mx <br/><br/>
- Webpage: [alejandro-ucan.netlify.app](https://alejandro-ucan.netlify.app)

---
# Goals of the Module



---
# Content


---
# Evaluation Plan

- __50%__ Exámenes Parciales Teóricos. <br/><br/>
- __20%__ Actividades, tareas y caso integrador. <br/><br/>
- __30%__ Examen Final Integrador.

---
# Bibliography:


